name: rpg_task_manager
description: "App that makes doing tasks easy and addicting"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.36 # To play audio
  provider: ^6.0.0 # To use inheritedWidget in simpler way

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # To change the app icon
  path_provider: ^2.0.0
  path: ^1.8.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/task_manager_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/icons/