name: rpg_task_manager
description: "App that makes doing tasks easy and addicting"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Аудио файл ашиглах, тоглуулах сан
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App-ын зургыг өөрчлөх сан
  flutter_launcher_icons: ^0.13.1

  path_provider: ^2.0.0
  path: ^1.8.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/task_manager_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/